1. Legen Sie eine Tabelle an, in der Sie Materialien für die Maschinen verwalten. Folgende Daten müssen gespeichert werden können: Name, zugehörige Maschine, Menge, letztes Einkaufsdatum

CREATE TABLE MATERIAL (
  MATERIAL_NUMMER INT PRIMARY KEY,
  NAME VARCHAR(20),
  MNR INT,
  MENGE INT,
  LAST_BUY_DATE DATE,
  FOREIGN KEY (MNR) REFERENCES MASCHINE (MNR)
 );

2. Fügen Sie drei Materialien ein
CREATE SEQUENCE MATERIAL_SEQ;

INSERT INTO MATERIAL VALUES (MATERIAL_SEQ.NEXTVAL, 'Holz', 12, 2, '01-nov-2015');
INSERT INTO MATERIAL VALUES (MATERIAL_SEQ.NEXTVAL, 'Metall', 11, 24, '01-nov-2015');
INSERT INTO MATERIAL VALUES (MATERIAL_SEQ.NEXTVAL, 'Gas', 23, 27, '01-nov-2015');


INSERT INTO MATERIAL (MATERIAL_NUMMER, NAME, MNR, MENGE, LAST_BUY_DATE) VALUES (MATERIAL_SEQ.NEXTVAL, 'Holz', 12, 2, '01-nov-2015'), (MATERIAL_SEQ.NEXTVAL, 'Metall', 11, 24, '01-nov-2015'), (MATERIAL_SEQ.NEXTVAL, 'Gas', 23, 27, '01-nov-2015');

3. Geben Sie alle Maschinennamen aus, für die es Material gibt.

SELECT DISTINCT MASCHINE.MNR, MASCHINE.NAME
FROM MASCHINE, MATERIAL
WHERE MASCHINE.MNR = MATERIAL.MNR AND MATERIAL.MENGE > 0;

4. Geben Sie alle Mitarbeiter aus, die nicht an Maschinen arbeiten.

SELECT *
FROM PERSONAL
WHERE PNR NOT IN (SELECT PNR FROM MASCHINE);

SELECT *
FROM PERSONAL LEFT JOIN MASCHINE ON PERSONAL.PNR = MASCHINE.PNR
WHERE MNR IS NULL;

5. Überlegen Sie sich, wie und wo Sie speichern können, wieviel Material wann für welche Maschine benutzt wurde. Legen Sie entsprechende Tabellen an oder ändern Sie bestehende. Fügen Sie dazu fünf Datensätze ein.

CREATE TABLE VERBRAUCHTES_MATERIAL (
	ID INT PRIMARY KEY,
	MENGE INT,
	DATUM DATE,
	MNR INT,
	MATERIAL_NUMMER INT,
	FOREIGN KEY (MNR) REFERENCES MASCHINE(MNR),
	FOREIGN KEY (MATERIAL_NUMMER) REFERENCES MATERIAL(MATERIAL_NUMMER)
);

CREATE SEQUENCE VERBRAUCHTES_MATERIAL_SEQ;
INSERT INTO VERBRAUCHTES_MATERIAL VALUES (VERBRAUCHTES_MATERIAL_SEQ.NEXTVAL, 1, '01-nov-2015', 12, 1);
INSERT INTO VERBRAUCHTES_MATERIAL VALUES (VERBRAUCHTES_MATERIAL_SEQ.NEXTVAL, 1, '01-nov-2015', 12, 1);
INSERT INTO VERBRAUCHTES_MATERIAL VALUES (VERBRAUCHTES_MATERIAL_SEQ.NEXTVAL, 3, '01-nov-2015', 11, 2);
INSERT INTO VERBRAUCHTES_MATERIAL VALUES (VERBRAUCHTES_MATERIAL_SEQ.NEXTVAL, 2, '01-nov-2015', 11, 2);
INSERT INTO VERBRAUCHTES_MATERIAL VALUES (VERBRAUCHTES_MATERIAL_SEQ.NEXTVAL, 10, '01-nov-2015', 23, 3);

6. Geben Sie eine Übersicht aus, wieviel die einzelnen Maschinen an Material verbraucht haben.

SELECT MNR, SUM(MENGE)
FROM VERBRAUCHTES_MATERIAL
GROUP BY MNR;

7. Wie muss die Tabelle in 1) geändert werden, wenn ein Material für verschiedene Maschinen benutzt werden kann? Formulieren Sie das dazugehörige SQL.

ALTER TABLE MATERIAL DROP COLUMN MNR;















