DROP TABLE PRAEMIE;
DROP TABLE KIND;
DROP TABLE MASCHINE;
DROP TABLE PERSONAL;
DROP TABLE ABTEILUNG;
DROP TABLE GEHALT;

CREATE TABLE PERSONAL (
  PNR INT PRIMARY KEY,
  VORNAME VARCHAR(20),
  NACHNAME VARCHAR(20),
  GEH_STUFE VARCHAR(5),
  ABT_NR VARCHAR(5),
  KRANKENKASSE VARCHAR(3),
  FOREIGN KEY (GEH_STUFE) REFERENCES GEHALT(GEH_STUFE),
  FOREIGN KEY (ABT_NR) REFERENCES ABTEILUNG(ABT_NR)
);

CREATE TABLE MASCHINE (
  MNR INT PRIMARY KEY,
  NAME VARCHAR(20),
  PNR INT,
  ANSCH_DATUM DATE,
  NEUWERT INT,
  ZEITWERT INT,
  FOREIGN KEY (PNR) REFERENCES PERSONAL(PNR)
);

CREATE TABLE KIND (
  PNR INT,
  K_NAME VARCHAR(20),
  K_VORN VARCHAR(20),
  K_GEB DATE,
  PRIMARY KEY (PNR, K_VORN, K_NAME),
  FOREIGN KEY (PNR) REFERENCES PERSONAL(PNR)
);

CREATE TABLE GEHALT (
  GEH_STUFE VARCHAR(5) PRIMARY KEY,
  BETRAG INT
);

CREATE TABLE ABTEILUNG (
  ABT_NR VARCHAR(5) PRIMARY KEY,
  NAME VARCHAR(30)
);

CREATE TABLE PRAEMIE (
  PNR INT,
  P_BETRAG INT,
  DATUM DATE,
  PRIMARY KEY (PNR, P_BETRAG, DATUM),
  FOREIGN KEY (PNR) REFERENCES PERSONAL(PNR)
);
